// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Yq2kqq4PyH5j5pJf3aVv3GGdnyCYccU',
    appId: '1:344268989554:web:018c98fb1e8e57c476ceeb',
    messagingSenderId: '344268989554',
    projectId: 'foodie-6dde9',
    authDomain: 'foodie-6dde9.firebaseapp.com',
    storageBucket: 'foodie-6dde9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnp5E-Vw5vpE3pvC5UBydxeFrQzsicnx0',
    appId: '1:344268989554:android:e2e55755b15d36ae76ceeb',
    messagingSenderId: '344268989554',
    projectId: 'foodie-6dde9',
    storageBucket: 'foodie-6dde9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9w7Jgxxiyit0NWnWejA_3gos6XGQW5M',
    appId: '1:344268989554:ios:27f395d86d5a901976ceeb',
    messagingSenderId: '344268989554',
    projectId: 'foodie-6dde9',
    storageBucket: 'foodie-6dde9.firebasestorage.app',
    iosBundleId: 'com.example.foodie2',
  );
}
